version: '3.8'

networks: 
  bubble:
    external: true

services:

  fitmap.function-v2:
    container_name: fitmap.function-v2
    image: maven:3-adoptopenjdk-11-openj9
    working_dir: /app
    networks:
      - bubble
    ports:
      - "8080:8080"
    volumes:
      - $PWD:/app
      - $HOME/.m2:/root/.m2
      - $HOME/gcp:$HOME/gcp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp/google_application_credentials.json
      - GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT
    entrypoint: mvn function:run -Drun.functionTarget=com.fitmap.function.v2.FitMapFunction
